### ISSUE TITLE
Custom Video Problem

### ISSUE THREAD

**Issue by YujxZJCN** [YairShemer/ILS-SUMM#1]
Could you please tell me how to generate shots_features.npy and shots_durations.npy?

**Comment by YairShemer** [comment]
From our paper ([ILS-SUMM: Iterated Local Search for Unsupervised Video Summarization](https://arxiv.org/abs/1912.03650)):
![image](https://user-images.githubusercontent.com/26732763/78102603-5ba4de00-73f3-11ea-811a-87fe34c75531.png)
For the RGB histogram feature extraction, we used [this function](https://github.com/YairShemer/ILS-SUMM/blob/master/datasets/gt%20auxiliary%20scripts/extract_features.py).
For the FFprob shot segmentation, we used [this function](https://github.com/YairShemer/ILS-SUMM/blob/master/datasets/gt%20auxiliary%20scripts/ffprob_shot_segmentation.py).
For the KTS shot segmentation, we used the code from [here](https://github.com/pathak22/videoseg/blob/master/src/vid2shots.py).

**Comment by Tramac** [comment]
How to generate shots_durations.npy?

**Comment by YairShemer** [comment]
You can use any shot segmentation method you prefer. We used KTS and FFprob as explained [above](https://github.com/YairShemer/ILS-SUMM/issues/1#issuecomment-607046119).
