### ISSUE TITLE
How can I create shot_segmentation.txt?

### ISSUE THREAD

**Issue by sontung2310** [YairShemer/ILS-SUMM#3]
I want to create shot_duration.npy of my custom video. But it requires shot_segmentation.txt.
Could you help me solve this problem?
Thanks in advance

**Comment by tuannguyen1999xxx** [comment]
I got this issue too, pls help.

**Comment by YairShemer** [comment]
The file shots_durations.npy contains an array that represents the number of frames in each shot. To create this array you may use any shot segmentation algorithm you choose.  
  

We chose the FFprob on some videos and KTS on others as explained in [our paper](https://arxiv.org/abs/1912.03650):   
![image](https://user-images.githubusercontent.com/26732763/78102603-5ba4de00-73f3-11ea-811a-87fe34c75531.png)   
  
For the FFprob shot segmentation, we used [this function](https://github.com/YairShemer/ILS-SUMM/blob/master/datasets/gt%20auxiliary%20scripts/ffprob_shot_segmentation.py).
For the KTS shot segmentation, we used the code from [here](https://github.com/pathak22/videoseg/blob/master/src/vid2shots.py).

**Comment by sontung2310** [comment]
But how can i create file 'shot_segmentation.txt' for running FFprob shot segmentation?

**Comment by YairShemer** [comment]
The `shot_segmentation.txt` file can be generated using the FFmpeg command, as demonstrated in [this function](https://github.com/YairShemer/ILS-SUMM/blob/master/datasets/gt%20auxiliary%20scripts/ffprob_shot_segmentation.py) (See lines 6-18).
