### ISSUE TITLE
number of frames in image directory

### ISSUE THREAD

**Issue by ibrahimrazu** [YairShemer/ILS-SUMM#5]
Hi,
Thanks again for sharing your work. I had a little confusion: 
using your script 'extract_features.py', its very handy to compute the features. However, i think the frames need to be extracted before. Does it matter if i use any fps to extract the frames? or it should be synchronous to the ffprob_shot_segmentation? 

Thanks again

**Comment by YairShemer** [comment]
You should use the fps of the specific video file (see [here](https://stackoverflow.com/questions/24361771/frame-rate-of-video-python) a way to get it). In that way, it will be synchronized with the ffprob shot segmentation.

**Comment by ibrahimrazu** [comment]
Thanks for confirming that 👍
